# file: $(VFC)/class/cpp/Dbgl/Makefile
#

# define the object files
#
OBJ = dbgl_00.o dbgl_01.o dbgl_02.o
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
current_dir := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))


print-%  : ; @echo $* = $($*)

